export const GET_USER = 'GET_USER';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'; 
export const GET_ORDERS_SINGLE_USER = 'GET_ORDERS_SINGLE_USER';