export const GET_USER = 'GET_USER';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'; 
export const GET_ORDER_DETAILS = 'GET_ORDER_DETAILS';
export const EMPTY_ORDER_DETAILS = 'EMPTY_ORDER_DETAILS';
export const GET_ATTR_NAMES = 'GET_ATTR_NAMES';
export const GET_ATTR_VALUES = 'GET_ATTR_VALUES';
 